### ISSUE TITLE
throw new TypeError('CLIENT_MISSING_INTENTS')

### ISSUE THREAD

**Issue by viminio** [Liga-dos-Programadores/Project-A#84]
$ npm start

> project-a@1.0.0 start C:\Users\Viagra\Desktop\Project-A
> node index.js

C:\Users\Viagra\Desktop\Project-A\node_modules\discord.js\src\client\Client.js:544
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (C:\Users\Viagra\Desktop\Project-A\node_modules\discord.js\src\client\Client.js:544:13)
    at new Client (C:\Users\Viagra\Desktop\Project-A\node_modules\discord.js\src\client\Client.js:73:10)
    at Object.<anonymous> (C:\Users\Viagra\Desktop\Project-A\index.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project-a@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project-a@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Viagra\AppData\Roaming\npm-cache\_logs\2021-10-02T08_36_03_411Z-debug.log

**Comment by putsbam** [comment]
Verifique a versão instalada do discord.js, no seu package.json. Se eu não me engano, a partir da v13, é preciso especificar Intents ao criar o Client, porém esse Bot é feito na v12, por isso não é preciso. Dê uma olhada na parte de [Intents.FLAGS](https://discord.js.org/#/docs/main/stable/class/Intents?scrollTo=s-FLAGS) na documentação. 

Ex.:

```
const { Client, Intents } = require('discord.js');
const client = new Client({ intents: [Intents.FLAGS.GUILDS] }); // Aqui, o client só vai iniciar com a flag GUILDS.
```
